version: "3.9"
services:
  activeMQ:
    restart: always
    privileged: true
    image: islandora/activemq:3.1.3
    ports:
      - 61613:61613
      - 61616:61616
      - 8161:8161
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/opt/activemq/data
    environment:
      ACTIVEMQ_AUDIT_LOG_LEVEL: 
      ACTIVEMQ_LOG_LEVEL: 
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: 123456aA
      ACTIVEMQ_WEB_ADMIN_NAME: admin
      ACTIVEMQ_WEB_ADMIN_PASSWORD: 123456aA
