version: '3.9'
services:
  mysql:
    image: mysql:8.2.0
    restart: always
    privileged: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456aA
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456aA
    volumes:
      - /opt/app/mysql/conf:/etc/mysql/conf.d
      - /opt/app/mysql/data:/var/lib/mysql
      - /opt/app/mysql/logs:/var/log/mysql
      - /opt/app/mysql/sql/init:/docker-entrypoint-initdb.d
      - /opt/app/mysql/sql/data:/sql
      - /etc/localtime:/etc/localtime:ro
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --skip-character-set-client-handshake
      --explicit_defaults_for_timestamp=true
    networks:
      - mynetwork
