version: '3.9'
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    privileged: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456aA
      MYSQL_DATABASE: airport_monitor
      MYSQL_USER: umetrip
      MYSQL_PASSWORD: 123456aA
    volumes:
      - /home/app/mysql/conf:/etc/mysql/conf.d
      - /home/app/mysql/data:/var/lib/mysql
      - /home/app/mysql/logs:/var/log/mysql
      - /home/app/mysql/sql/init:/docker-entrypoint-initdb.d
      - /home/app/mysql/sql/data:/sql
      - /etc/localtime:/etc/localtime:ro
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "-usequelize_test", "-psequelize_test", "status"]
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      - mynetwork
