version: "3.3"

services:
  nginx:
    image: nginx:1.25.3
    restart: always
    privileged: true
    ports:
      - 80:80
    volumes:
      - /opt/app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/app/nginx/dist:/usr/share/nginx/html
      - /opt/app/nginx/logs:/var/log/nginx
    networks:
      - mynetwork
