version: "3"
services:
  pulsar:
    image: apachepulsar/pulsar-all:3.2.0
    container_name: "pulsar_standalone"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
    ports:
      - "6650:6650"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: bash -c "bin/pulsar standalone"
