version: "3.9"
services:
  rabbitmq:
    restart: always
    privileged: true
    container_name: rabbitmq
    image: rabbitmq:3.9.29-management
    #volumes:
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456aA
