version: "3.9"
services:
  rabbitmq:
    restart: always
    privileged: true
    container_name: rabbitmq
    image: rabbitmq:3.9.29-management
    volumes:
      - /mnt/data/rabbitmq/home:/var/lib/rabbitmq
      - /mnt/data/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    ports:
      - "5672:5672"
      - "15672:15672"
