version: "3.9"
services:
  zlmediakit:
    restart: always
    privileged: true
    image: zlmediakit/zlmediakit:master
    ports:
      - 1935:1935
      - 8089:80
      - 8443:443
      - 8554:554
      - 10000:10000
      - 10000:10000/udp
      - 8000:8000/udp
      - 9000:9000/udp
    volumes:
      - ./config:/config
      - ./logs:/log
      - ./media:/media
