version: "3.9"
services:
  zlmediakit:
    restart: always
    privileged: true
    image: zlmediakit/zlmediakit:master
    ports:
      - 1935:1935
      - 8440:80
      - 8443:443
      - 8554:554
      - 10000:10000
      - 10000:10000/udp
      - 8000:8000
      - 8000:8000/udp
      - 9000:9000/udp
      - 30000-30500:30000-30500
      - 30000-30500:30000-30500/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf:/opt/media/conf
      - ./logs:/opt/media/bin/log
      - ./conf/zlmedia.pem:/opt/media/bin/default.pem
